dnouri/nolearn

nolearn/lasagne.py
nolearn/tests/test_lasagne.py

An attempt at addressing #33: We don't want to pickle the Theano functions that `_create_iter_funcs` creates.  So we remove them before pickling and initialize again on `__setstate__`.

Dont pickle iter funcs

---

nolearn/lasagne.py
nolearn/tests/test_lasagne.py

initialize_layers() will now optionally accept an 'incoming' parameter for
layers.  A string or a list of strings may be used to refer to layers other
than the previous one.  This allows for more interesting architectures than
just the tower.

Allow specifying 'incoming' layer(s).

---

nolearn/lasagne.py
nolearn/metrics.py
nolearn/tests/test_lasagne.py
nolearn/tests/test_metrics.py
requirements.txt

Adds a more interesting interface for specifying losses.  The `loss` parameter is now deprecated, and one should use `objective` instead.  Here's an example of an 'Objective' implementation from `nolearn.lasagne` itself.
```python
class LossObjective(object):
def __init__(self, loss_function):
self.loss_function = loss_function
def __call__(self, layers, X, y, deterministic=False):
output_layer = layers['output']
return self.loss_function(
output_layer.get_output(X, deterministic=deterministic), y)
```
@cancan101 Let me know if this makes sense to you, and if it would fix #14.

Replace 'loss' parameter by 'objective' which has a more interesting interface.

---

nolearn/lasagne/base.py
nolearn/tests/test_lasagne.py

1) Input layer may now have a name other than 'input'.
2) The 'input_shape' kwarg to NeuralNet is no longer required.

Fix two bugs with handling input layers.

---

nolearn/lasagne/base.py
nolearn/tests/test_lasagne.py

Specifically, it will match layers by name and copy weights if names match,
instead of the brute-force approach using list indices, which doesn't work
reliably in some cases.
Aims to supercede #77.  Still needs better testing and possibly a way to
override some of the matching.

A new 'load_params_from' is more clever about loading weights.

---

nolearn/lasagne/__init__.py
nolearn/lasagne/base.py
nolearn/lasagne/handlers.py
nolearn/lasagne/util.py
nolearn/tests/test_lasagne.py

By default, PrintLayerInfo is added, which prints the usual layer information for non-CNN.  For CNN, if verbosity >= 2, print additional information about image coverage and capacity.  If verbosity >= 3, even more information about receptive field size and real filter size.  For more, see link to work by Xudong Cao.

Added on_training_started feature. 

---

nolearn/lasagne/base.py

Hi Daniel,
I had problems pickling my networks when using a largish data set. I found the problem to be connected with the Batchiterator which holds a reference to the whole training set and which thus also gets pickled. The current pickle protocol available for python 2.7 can't handle too large arrays (see e.g. [here](https://groups.google.com/forum/#!topic/theano-users/b8C33U4skXI)). 
Since the X and y are set in the `__call__` method, I think they can be removed from `__getstate__`.

Don't pickle X and y  when pickling BatchIterator.

---

nolearn/lasagne/handlers.py

blue is not (always?) shown in ipython notebooks.

Patch: Change color for best train loss from blue to cyan

---

.travis.yml
nolearn/lasagne/base.py
nolearn/lasagne/tests/test_base.py

Here's an example of what this allows.  Note that there's two input layers, and that we pass a dict instead of a single array X when calling fit and predict.
```python
net = NeuralNet(
layers=[
(InputLayer,
{'name': 'input1', 'shape': (None, 392)}),  # !
(DenseLayer,
{'name': 'hidden1', 'num_units': 98}),
(InputLayer,
{'name': 'input2', 'shape': (None, 392)}),  # !
(DenseLayer,
{'name': 'hidden2', 'num_units': 98}),
(ConcatLayer,
{'incomings': ['hidden1', 'hidden2']}),
(DenseLayer,
{'name': 'hidden3', 'num_units': 98}),
(DenseLayer,
{'name': 'output', 'num_units': 10, 'nonlinearity': softmax}),
],
update=nesterov_momentum,
update_learning_rate=0.01,
update_momentum=0.9,
max_epochs=2,
)
X, y = mnist
X_train, y_train = X[:10000], y[:10000]
X_train1, X_train2 = X_train[:, :392], X_train[:, …
```

Allow for multiple input layers.

---

nolearn/lasagne/__init__.py
nolearn/lasagne/base.py
nolearn/lasagne/handlers.py
nolearn/lasagne/tests/test_base.py
nolearn/lasagne/util.py
nolearn/lasagne/visualize.py
requirements.txt

This catches up with the deprecation of the `lasagne.objectives.Objective` class and introduces a new `objective` interface along with a default implementation:
```python
def objective(layers,
loss_function,
target,
aggregate=aggregate,
**kwargs):
output_layer = layers[-1]
network_output = get_output(output_layer, **kwargs)
losses = loss_function(network_output, target)
return aggregate(losses)
```
A custom function can be passed as the `objective` parameter.
What do people think of this latest iteration on objective/loss?  ping @erogol @BrianMiner @bobchennan @BenjaminBossan @cancan101

Remove support for Lasagne's deprecated 'Objective' class.

---

nolearn/lasagne/handlers.py

…this allows us to do things like 'PrintLayerInfo()(net)' instead of 'PrintLayerInfo()(net, None)', which can be useful sometimes.
For instance, when just want to see the information about the net without calling fit, we can use this.

Changed the train_history_ to be None by default for PrintLayerInfo

---

nolearn/lasagne/base.py
nolearn/lasagne/tests/test_base.py

As suggested in https://github.com/Lasagne/Lasagne/issues/12#issuecomment-136338948

Add NeuralNet.partial_fit method that trains for only one epoch

---

nolearn/lasagne/base.py
nolearn/lasagne/tests/test_base.py

Legacy layer initialization is now also triggered if layer name is unicode in Python 2.7.

Legacy init with unicode

---

nolearn/lasagne/tests/conftest.py
nolearn/lasagne/tests/test_visualize.py
nolearn/lasagne/visualize.py

Now assumes that the number of classes is determined by `get_output_shape(layers_[-1])[1]`.
Should address this [issue](https://github.com/dnouri/nolearn/issues/172).

Fix a bug that prevented `plot_occlusion` from working when last layer did not have the `num_units` attribute

---

nolearn/lasagne/handlers.py

Fix a minor bug in PrintLayerInfo handler in which the layer numbers were not printed if a lasagne Layer instance was passed to the network constructor as the layer parameter

Fixes #249

---

nolearn/lasagne/base.py
nolearn/lasagne/tests/test_base.py

List of changes:
* fixed a bug that occurred when not using `TrainSplit(0)`, which was introduced in a [recent PR](https://github.com/dnouri/nolearn/pull/248)
* add test to catch this kind of error
* add line breaks in base.by

Fixed bug that occurred when not using validation data

---

nolearn/lasagne/tests/conftest.py
nolearn/lasagne/tests/test_visualize.py
nolearn/lasagne/visualize.py

List of changes:
* fix bug in several plotting functions that occurs when a conv layer only has 1 filter
* some formatting in `visualize.py`
* use `interpolation='none'` in `visualize.py`
* minor refactoring of tests in `test_visualize.py` (unfortunately, pytest fixtures and parametrize don't cooperate, may change in the future)
This fix should address [this issue](https://github.com/dnouri/nolearn/issues/246).

Plotting functions works even when a conv layer with 1 filter is used

---

nolearn/lasagne/base.py
nolearn/lasagne/tests/test_base.py

Networks with multiple outputs can now be defined simply by passing a list of Layer instances as the layers parameter.  The networks _output_layer is set to the last layer in the list
Pertains to dnouri/nolearn#202

Added basic support for multiple outputs

---

nolearn/lasagne/base.py
nolearn/lasagne/tests/test_base.py

Allows:
```python
nn = NeuralNet(
layers=[
('lasagne.layers.InputLayer', {'shape': (None, 10)}),
('lasagne.layers.DenseLayer', {'num_units': 33}),
],
)
```

Allow layer types to be passed as string

---

nolearn/lasagne/base.py
nolearn/lasagne/tests/test_base.py

NeuralNet.score now uses sklearn.metrics.r2_score (fix #280)

---

nolearn/lasagne/tests/test_handlers.py
nolearn/lasagne/util.py

`util.get_conv_infos` made the implicit assumption that all shapes are at least 2D, now deals with 1D also. Was triggered when a CNN with verbosity 2 or higher contained a 1D output. Now, `'0'` is returned when such an output is encountered.

Fix bug in get_conv_infos

---

README.rst

In Readme, it should be https://raw.githubusercontent.com/dnouri/nolearn/0.6.0/requirements.txt rather than https://github.com/dnouri/nolearn/tree/0.6.0/requirements.txt
ValueError: ('Missing distribution spec', '<!DOCTYPE html>')
I got an error on ubuntu at least.

Should raw.githubusercontent for pip -r

---

nolearn/lasagne/base.py

This is useful when your (sole) loss function doesn't depend on labels

Allow for unused inputs to train function

---

nolearn/lasagne/visualize.py

If the user has specified a custom name for the layer, use that name as the node label when creating the "PyDot Graph". If no custom name is specified, use the layer class name as the label for the node.

Use the name of the lasagne layer as node label

---

setup.py

This is a suggested fix for #335 - we just make gdbn an extra require so the core package can be installed without it.
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

Making gdbn an extra require
