.travis.yml, nolearn/lasagne/utils.py, nolearn/lasagne/visualize.py, nolearn/tests/conftest.py, nolearn/tests/test_lasagne.py, setup.py
(Supercedes #74)
Create new visualize.py and utils.py
Added some visualization functions for convenience:
plot_loss: Plot train loss and valid loss
plot_weights: Plot the filters of a convolutional layer
plot_activity: Plot activity of a convolutional layer produced by a sample
plot_occlusion: For image samples, shows which part of the images are crucial for the prediction
Requires a utility function:
occlusion_heatmap: Creates a heatmap of where an occlusion affects the prediction
Tests only check whether plotting with different options does not raise an exception.
=> Feature visualization

nolearn/lasagne/base.py, nolearn/lasagne/visualize.py, nolearn/tests/test_lasagne.py, requirements.txt
Training info now in a slightly different format, uses tabulate package. This makes it easier to modify the train info (no need for string interpolation or anything).
Added possibility to add custom score to the train info (for instance, use parameter custom_score=('mean abs error', <func mean_abs_error>)).
=> Feature train info

nolearn/lasagne/base.py
The PrintLayerInfo now takes care of that.
=> Patch: Remove now superfluous _print_layer_info.

nolearn/lasagne/base.py, nolearn/lasagne/handlers.py, nolearn/lasagne/tests/test_base.py
When verbose, load_params now alerts the user about whether parameters could or could not be loaded successfully into the current net.
=> Feature verbose load params

nolearn/lasagne/base.py
=> Variable cleanup in _create_iter_funcs

nolearn/lasagne/tests/test_visualize.py, nolearn/lasagne/visualize.py
Also improved docs and readability of visualize.py and adjusted unit tests.
=> Fixed a bug in occlusion_heatmap

nolearn/lasagne/tests/test_visualize.py, nolearn/lasagne/visualize.py
Now "epoch" label for x axis and "loss" label for y axis.
Added functionality to allow different labels for plot_occlusion when passing more than one sample.
=> Axes labels for plot_loss.

nolearn/lasagne/__init__.py, nolearn/lasagne/base.py, nolearn/lasagne/tests/test_base.py
An alternative to "train_test_splitter done using composition" #118
=> Allow passing of TrainSplit (train_test_split before) as parameter

nolearn/lasagne/util.py
Refers to https://github.com/dnouri/nolearn/issues/115
=> Fix deprecation warning caused by use of numpy.negative.

nolearn/lasagne/base.py, nolearn/lasagne/tests/test_base.py
=> For regression problems, allow y.ndim == 1

nolearn/lasagne/tests/test_base.py
Just added the asserts, tests still pass.
=> Fixed: missing asserts in test_base.

nolearn/lasagne/base.py, nolearn/lasagne/tests/conftest.py, nolearn/lasagne/tests/test_base.py
As discussed in https://github.com/Lasagne/Lasagne/issues/12#issuecomment-136217320
=> Allow passing a Lasagne layer instance as the 1st arg to NeuralNet

nolearn/lasagne/base.py, nolearn/lasagne/tests/test_base.py
Used to return a list, which might be unexpected by some.
=> Slicing a Layers object now returns a Layers object

nolearn/lasagne/tests/conftest.py, nolearn/lasagne/tests/test_visualize.py, nolearn/lasagne/visualize.py
`plot_occlusion` now works with colored images and/or images that are not square.
=> Improve plot_occlusion

nolearn/lasagne/visualize.py
Used to pre-allocate c * s0 * s0 * s1 * s1 array, where c, s0, s1 == image.shape[2:]. This is quite a lot for larger images (256x256 colored image took more than 40gb). Now only pre-allocates c * s0 * s1 * s1 array.
=> plot_occlusion how requires less memory

nolearn/lasagne/visualize.py
Return the plot so that it is possible to modify/save the figures
=> Return plot

nolearn/lasagne/__init__.py, nolearn/lasagne/base.py, nolearn/lasagne/tests/test_base.py
Borrows the idea from here: https://groups.google.com/forum/#!msg/lasagne-users/2z-6RrgiHkE/lHghzLDgCgAJ
=> Allow gradients to be scaled per layer

nolearn/lasagne/base.py, nolearn/lasagne/handlers.py, nolearn/lasagne/tests/test_base.py, nolearn/lasagne/tests/test_handlers.py
I couldn't get all the other commits to squash properly in #135 , so I removed the branch and started again. This is the clean version.
=>  Add support for multiple custom scores to be passed through the custom_scores parameter (take 2)

nolearn/lasagne/handlers.py
See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/lasagne-users/z7g0EIHwYcI/9GgV6AKXBAAJ
=> Use 'trainable' parameters when reporting number

nolearn/lasagne/base.py, nolearn/lasagne/tests/test_base.py
See also config.reoptimize_unpickled_function http://deeplearning.net/software/theano/library/config.html#config.reoptimize_unpickled_function
See also #33 which asked for the change
=> Back to including the Theano graph in NeuralNet pickles

requirements.txt, setup.cfg, setup.py
Use 'pip install -e .[visualization]' or similar to install.
=> Move visualization dependencies (matplotlib) into extras_require

nolearn/lasagne/base.py
For #247.
This PR changes the way the losses are aggregated. Now it will keep track of the sample per batch and use that as the weights when calculating the average.
The current calculation is slightly inaccurate under these circumstances.
1. `batch_size` is very large or the number of batches is small
2. losses is very noisy
3. the last batch has very few samples
I do not see any relevant tests related to loss calculation so I haven't add any. If you can give me some pointers about where to add them, I can write some.
=> Fix inaccurate loss calculation

nolearn/lasagne/base.py, nolearn/lasagne/handlers.py, nolearn/lasagne/tests/test_base.py, nolearn/lasagne/tests/test_handlers.py
Usage example:
```python
from lasagne.objectives import squared_error
net = NeuralNet(
scores_train=[('sq', squared_error)]
)
```
=> Extra scores can now be computed as part of Theano computation graph

nolearn/lasagne/visualize.py
Defer the import to function call rather than module load
=> Removes hard dependency of pydotplus and ipython.

nolearn/lasagne/base.py, nolearn/lasagne/tests/test_base.py
=> Network.predict works with multi-outputs (contd.)

nolearn/lasagne/handlers.py
https://github.com/dnouri/nolearn/issues/301
=> Fixed Issue #301

nolearn/lasagne/base.py, nolearn/lasagne/tests/test_base.py
See this issue: https://github.com/dnouri/nolearn/issues/316
=> Fix bug that prevents use of mask_input parameter when string is passed.

setup.py
Dürr in README.rst caused ascii decode error.
=> allow utf-8 encoded chars

nolearn/lasagne/base.py
=> fix ignores
